# SLF4J Simple Logger Configuration
org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.org.joykabir.ssl=info
org.slf4j.simpleLogger.log.org.joykabir.ssl.server=debug
org.slf4j.simpleLogger.log.org.joykabir.ssl.client=info
org.slf4j.simpleLogger.log.org.joykabir.ssl.cert=info
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss.SSS
org.slf4j.simpleLogger.showThreadName=true
org.slf4j.simpleLogger.showLogName=true
org.slf4j.simpleLogger.showShortLogName=true
org.slf4j.simpleLogger.levelInBrackets=true
org.slf4j.simpleLogger.logFile=System.out
org.slf4j.simpleLogger.log.org.apache.hc=warn
org.slf4j.simpleLogger.log.org.apache.http=warn
org.slf4j.simpleLogger.log.sun.net.httpserver=warn
org.slf4j.simpleLogger.log.com.sun.net.httpserver=warn
org.slf4j.simpleLogger.log.org.slf4j=warn
org.slf4j.simpleLogger.cacheOutputStream=true